Repository volis-o/test-prow, pull requests merged in 2023-07, with the labels that each got.

#1 Create test.md
  test.md
Labels: lgtm, approved

#2 Update test.md
  test.md
Labels: lgtm, approved

#3 Update test.md
  test.md
Labels: kind/bug, lgtm, approved, size/XS

#4 Format test.md
  test.md
Labels: kind/cleanup, lgtm, approved
